services:
  todo-list:
    image: node:24-alpine
    ports:
      - 0.0.0.0:5173:5173
    working_dir: /app
    command: sh -c "npm install && npx vite --host 0.0.0.0 && npm run dev"
    develop:
      watch:
        - action: sync
          initial_sync: true
          path: .
          target: /app
          ignore:
            - node_modules/
